<?php
/**
*@author Amanda  
*@date Wed May 17 21:42:06 GMT-04:00 2023  
*@time Wed May 17 21:42:06 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla person.
 *
 * Los siguientes son los campos de la tabla 'person':
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $sex
 * @property integer $age
 * @property string $email

 * Los siguientes son las relaciones de este modelo :

 **/



class Person extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'person';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'database';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = [];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Person';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'first_name',
      'last_name',
      'sex',
      'age',
      'email'
    ];



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'first_name' =>'required|max:255',
                'last_name' =>'required|max:255',
                'sex' =>'required|max:20',
                'age' =>'required',
                'email' =>'required|max:255'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.person,id,'.$this->id.',id',
                'first_name' =>'required|max:255',
                'last_name' =>'required|max:255',
                'sex' =>'required|max:20',
                'age' =>'required',
                'email' =>'required|max:255'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

